# Generated by Django 5.1.1 on 2024-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("cover_image", models.ImageField(upload_to="album_covers/")),
                ("release_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
