# Generated by Django 5.1.1 on 2024-12-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="artists/")),
                ("genre", models.CharField(default="Unknown", max_length=50)),
                ("profile_url", models.URLField(default="#")),
            ],
        ),
    ]
