# Generated by Django 5.1.1 on 2024-12-13 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0004_likedsong"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="likedsong",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="frontend.track",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="likedsong",
            unique_together={("user", "track")},
        ),
    ]
