# Generated by Django 5.1.1 on 2024-12-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0005_alter_likedsong_track_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="genre_backgrounds/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
