# Generated by Django 5.1.1 on 2024-12-15 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0006_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="genre",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="frontend.genre",
            ),
            preserve_default=False,
        ),
    ]
