# Generated by Django 5.1.1 on 2024-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0007_track_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="play_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
