# Generated by Django 5.1.1 on 2024-12-24 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0010_playlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="frontend.album",
            ),
        ),
    ]
