# Generated by Django 5.1.1 on 2024-12-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0011_alter_track_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
