# Generated by Django 5.1.1 on 2025-01-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0013_preference_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("listener", "Listener"), ("musician", "Musician")],
                default="listener",
                max_length=10,
            ),
        ),
    ]
